remote_theme: pages-themes/hacker@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
title: Ursus
description: We are Gruberx_Crew, a passionate and close-knit team of like-minded people.
